using P3D_Scenario_Generator.ConstantsEnums;
using P3D_Scenario_Generator.Models;
using System.Xml.Serialization;

namespace P3D_Scenario_Generator.Services
{
    public class ScenarioXML(AssetFileGenerator assetFileGenerator)
    {
        // Guard clauses to validate the constructor parameters.
        private readonly AssetFileGenerator _assetFileGenerator = assetFileGenerator ?? throw new ArgumentNullException(nameof(assetFileGenerator));

        private readonly SimBaseDocumentXML _simBaseDocumentXML = new();

        public void SetSimbaseDocumentXML(ScenarioFormData formData, Overview overview)
        {
            _simBaseDocumentXML.Type = "MissionFile";
            _simBaseDocumentXML.Descr = $"This is a {formData.ScenarioImageFolder} scenario generated by {Constants.appTitle}. Estimated time to complete: {ScenarioHTML.GetDuration(overview)} minutes.";
            _simBaseDocumentXML.Title = $"{overview.Title}";

            _simBaseDocumentXML.WorldBaseFlight = new WorldBaseFlight();
        }

        public void WriteXML(ScenarioFormData formData)
        {
            // 1. Setup clean namespaces to avoid xmlns:xsi and xmlns:xsd
            XmlSerializerNamespaces ns = new();
            ns.Add("", "");

            XmlSerializer xmlSerializer = new(_simBaseDocumentXML.GetType());

            // 2. Use Path.Combine for path safety
            string filePath = Path.Combine(formData.ScenarioFolder, $"{formData.ScenarioTitle}.xml");

            // 3. Serialize directly with empty namespaces
            using StreamWriter writer = new(filePath);
            xmlSerializer.Serialize(writer, _simBaseDocumentXML, ns);
            // StreamWriter is closed automatically by 'using'
        }

        #region Object creation/editing utilities

        public static AttachedWorldPosition GetAttachedWorldPosition(string worldPosition, string AltitudeIsAGL)
        {
            AttachedWorldPosition awp = new(worldPosition, AltitudeIsAGL);
            return awp;
        }

        public static string GetGateOrientation(Gate gate)
        {
            return $"{string.Format("{0:0.0}", gate.pitch)},0.0,{string.Format("{0:0.0}", gate.orientation)}";
        }

        public static string GetGateWorldPosition(Gate gate, double vertOffset)
        {
            return $"{ScenarioFXML.FormatCoordXML(gate.lat, "N", "S", false)},{ScenarioFXML.FormatCoordXML(gate.lon, "E", "W", false)},+{gate.amsl + vertOffset}";
        }

        public static string GetGUID()
		{
            Guid guid = Guid.NewGuid();
			string guidUpper = guid.ToString().ToUpper();
            return $"{{{guidUpper}}}";
        }

        public ObjectReference GetObjectReference(string objName, string search)
        {
            ObjectReference or = new();
            int idIndex;
            switch (objName)
            {
                case "AirportLandingTrigger":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionAirportLandingTrigger.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionAirportLandingTrigger[idIndex].InstanceId);
                    break;
                case "CloseWindowAction":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionCloseWindowAction.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionCloseWindowAction[idIndex].InstanceId);
                    break;
                case "CylinderArea":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionCylinderArea.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionCylinderArea[idIndex].InstanceId);
                    break;
                case "DialogAction":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionDialogAction.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionDialogAction[idIndex].InstanceId);
                    break;
                case "Goal":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionGoal.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionGoal[idIndex].InstanceId);
                    break;
                case "GoalResolutionAction":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionGoalResolutionAction.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionGoalResolutionAction[idIndex].InstanceId);
                    break;
                case "LibraryObject":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SceneryObjectsLibraryObject.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SceneryObjectsLibraryObject[idIndex].InstanceId);
                    break;
                case "ObjectActivationAction":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionObjectActivationAction.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionObjectActivationAction[idIndex].InstanceId);
                    break;
                case "OneShotSoundAction":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionOneShotSoundAction.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionOneShotSoundAction[idIndex].InstanceId);
                    break;
                case "OnScreenText":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionOnScreenText.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionOnScreenText[idIndex].InstanceId);
                    break;
                case "OpenWindowAction":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionOpenWindowAction.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionOpenWindowAction[idIndex].InstanceId);
                    break;
                case "PointOfInterest":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionPointOfInterest.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionPointOfInterest[idIndex].InstanceId);
                    break;
                case "PointOfInterestActivationAction":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionPointOfInterestActivationAction.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionPointOfInterestActivationAction[idIndex].InstanceId);
                    break;
                case "ProximityTrigger":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger[idIndex].InstanceId);
                    break;
                case "RectangleArea":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionRectangleArea.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionRectangleArea[idIndex].InstanceId);
                    break;
                case "ScaleformPanelWindow":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionScaleformPanelWindow.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionScaleformPanelWindow[idIndex].InstanceId);
                    break;
                case "ScriptAction":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionScriptAction.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionScriptAction[idIndex].InstanceId);
                    break;
                case "TimerTrigger":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionTimerTrigger.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionTimerTrigger[idIndex].InstanceId);
                    break;
                case "UIPanelWindow":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionUIPanelWindow.FindIndex(o => o.Descr == search);
                    or = new(_simBaseDocumentXML.WorldBaseFlight.SimMissionUIPanelWindow[idIndex].InstanceId);
                    break;
                default:
                    break;
            }
            return or;
        }

        static public string[] GetWindowParameters(int windowWidth, int windowHeight, WindowAlignment alignment, int monitorWidth, int monitorHeight, int offset)
        {
            int horizontalOffset, verticalOffset;
            // Offsets
            if (alignment == WindowAlignment.TopLeft)
            {
                horizontalOffset = offset;
                verticalOffset = offset;
            }
            else if (alignment == WindowAlignment.TopRight)
            {
                horizontalOffset = monitorWidth - offset - windowWidth;
                verticalOffset = offset;
            }
            else if (alignment == WindowAlignment.BottomRight)
            {
                horizontalOffset = monitorWidth - offset - windowWidth;
                verticalOffset = monitorHeight - offset - windowHeight;
            }
            else if (alignment == WindowAlignment.BottomLeft)
            {
                horizontalOffset = offset;
                verticalOffset = monitorHeight - offset - windowHeight;
            }
            else // alignment == "Centered"
            {
                horizontalOffset = monitorWidth / 2 - windowWidth / 2;
                verticalOffset = monitorHeight / 2 - windowHeight / 2;
            }

            return [windowWidth.ToString(), windowHeight.ToString(), horizontalOffset.ToString(), verticalOffset.ToString()];
        }

        public void SetAirportLandingTrigger(string descr, string landingType, string activated, string airportIdent)
        {
            List<ObjectReference> orList = [];
            SimMissionAirportLandingTrigger alt = new(descr, landingType, activated, new Actions(orList), GetGUID(), airportIdent, null);
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionAirportLandingTrigger != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionAirportLandingTrigger.Add(alt);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionAirportLandingTrigger = [alt];

        }

        public void SetAirportLandingTriggerAction(string objName, string orSearch, string tSearch)
        {
            ObjectReference or = GetObjectReference(objName, orSearch);
            int idIndex;
            idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionAirportLandingTrigger.FindIndex(o => o.Descr == tSearch);
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionAirportLandingTrigger[idIndex].Actions != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionAirportLandingTrigger[idIndex].Actions.ObjectReference.Add(or);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionAirportLandingTrigger[idIndex].Actions = new Actions([or]);
        }

        public void SetAttachedWorldPosition(string objName, string search, AttachedWorldPosition wp)
        {
            int idIndex;
            switch (objName)
            {
                case "CylinderArea":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionCylinderArea.FindIndex(o => o.Descr == search);
                    _simBaseDocumentXML.WorldBaseFlight.SimMissionCylinderArea[idIndex].AttachedWorldPosition = wp;
                    break;
                case "RectangleArea":
                    idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionRectangleArea.FindIndex(o => o.Descr == search);
					_simBaseDocumentXML.WorldBaseFlight.SimMissionRectangleArea[idIndex].AttachedWorldPosition = wp;
                    break;
                default:
                    break;
            }
        }

        public void SetCloseWindowAction(int index, string objName, string search)
        {
            search = $"{search}{index:00}";
            ObjectReference or = GetObjectReference(objName, search);
            SimMissionCloseWindowAction cwa = new($"Close{search}", or, GetGUID());
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionCloseWindowAction != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionCloseWindowAction.Add(cwa);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionCloseWindowAction = [cwa];
        }

        public void SetCylinderArea(int index, string descr, string orientation, string radius, string height, string drawStyle)
        {
            descr = $"{descr}{index:00}";
            SimMissionCylinderArea ca = new(descr, orientation, radius, height, drawStyle, new AttachedWorldPosition(), GetGUID());
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionCylinderArea != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionCylinderArea.Add(ca);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionCylinderArea = [ca];
        }

        public void SetDialogAction(string descr, string text, string delay, string soundType)
        {
            SimMissionDialogAction da = new(descr, text, delay, soundType, GetGUID());
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionDialogAction != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionDialogAction.Add(da);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionDialogAction = [da];
        }

        public void SetDisabledTrafficAirports(string airportIdent)
        {
            SimMissionDisabledTrafficAirports dta = new(airportIdent);
            _simBaseDocumentXML.WorldBaseFlight.SimMissionDisabledTrafficAirports = dta;
        }

        public void SetPointOfInterest(int index, string objName, string search, string offsetXYZ, string curSel, string activated, string targetName)
        {
            search = $"{search}{index:00}";
            targetName = $"{targetName}{index:00}";
            ObjectReference or = GetObjectReference(objName, search);
			AttachedWorldObject awo = new(or, offsetXYZ);
            SimMissionPointOfInterest poi = new($"POI{index:00}", targetName, curSel, awo, GetGUID(), activated, index);
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionPointOfInterest != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionPointOfInterest.Add(poi);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionPointOfInterest = [poi];
        }

        public void SetGoal(string descr, string text)
        {
            SimMissionGoal g = new(descr, text, GetGUID());
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionGoal != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionGoal.Add(g);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionGoal = [g];
        }

        public void SetGoalResolutionAction(string search)
        {
            ObjectReference or = GetObjectReference("Goal", search);
            List <ObjectReference> orList = new([or]);
			SimMissionGoalResolutionAction gra = new("Completed", search, new Goals(orList), GetGUID());
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionGoalResolutionAction != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionGoalResolutionAction.Add(gra);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionGoalResolutionAction = [gra];
        }

        public void SetLibraryObject(int index, string descr, string mdlGUID, string worldPos, string orient, string altIsAGL, string scale, string isAct)
        {
			descr = $"{descr}{index:00}";
            SceneryObjectsLibraryObject lo = new(descr, mdlGUID, worldPos, orient, altIsAGL, scale, GetGUID(), isAct);
            if (_simBaseDocumentXML.WorldBaseFlight.SceneryObjectsLibraryObject != null)
                _simBaseDocumentXML.WorldBaseFlight.SceneryObjectsLibraryObject.Add(lo);
            else
                _simBaseDocumentXML.WorldBaseFlight.SceneryObjectsLibraryObject = [lo];
        }

        public void SetObjectActivationAction(int index, string objName, string search, string descr, string newObjectState)
        {
            search = $"{search}{index:00}";
            descr = $"{descr}{index:00}";
            ObjectReference or = GetObjectReference(objName, search);
			ObjectReferenceList orList = new([or]);
			SimMissionObjectActivationAction oaa = new(descr, orList, GetGUID(), newObjectState);
			if (_simBaseDocumentXML.WorldBaseFlight.SimMissionObjectActivationAction != null )
				_simBaseDocumentXML.WorldBaseFlight.SimMissionObjectActivationAction.Add(oaa);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionObjectActivationAction = [oaa];
        }

        public void SetOneShotSoundAction(int index, string descr, string soundFile)
        {
            descr = $"{descr}{index:00}";
            SimMissionOneShotSoundAction ossa = new(descr, soundFile, GetGUID());
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionOneShotSoundAction != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionOneShotSoundAction.Add(ossa);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionOneShotSoundAction = [ossa];
        }

        public void SetOnScreenText(string descr, string text, string onScrLoc, string RGBcol, string activated, string backCol)
        {
            SimMissionOnScreenText ost = new(descr, text, onScrLoc, RGBcol, activated, backCol, GetGUID());
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionOnScreenText != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionOnScreenText.Add(ost);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionOnScreenText = [ost];
        }

        public void SetOpenWindowAction(int index, string objName, string search, string[] windowParameters, string monitorNo)
        {
            search = $"{search}{index:00}";
            SetWindowSize sws = new(windowParameters[0], windowParameters[1]);
            SetWindowLocation swl = new(windowParameters[2], windowParameters[3]);
            ObjectReference or = GetObjectReference(objName, search);
			SimMissionOpenWindowAction owa = new($"Open{search}", sws, swl, monitorNo, or, GetGUID());
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionOpenWindowAction != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionOpenWindowAction.Add(owa);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionOpenWindowAction = [owa];
        }

        public void SetPOIactivationAction(int index, string objName, string search, string descr, string newObjectState)
        {
            search = $"{search}{index:00}";
            descr = $"{descr}{index:00}";
            ObjectReference or = GetObjectReference(objName, search);
            ObjectReferenceList orList = new([or]);
			SimMissionPointOfInterestActivationAction paa = new(descr, orList, GetGUID(), newObjectState);
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionPointOfInterestActivationAction != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionPointOfInterestActivationAction.Add(paa);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionPointOfInterestActivationAction = [paa];
        }

        public void SetProximityTrigger(int index, string descr, string activated)
        {
            descr = $"{descr}{index:00}";
            List<ObjectReference> aList = [];
            List<ObjectReference> enterList = [];
            List<ObjectReference> exitList = [];
            SimMissionProximityTrigger pt = new(descr, new Areas(aList), new OnEnterActions(enterList), GetGUID(), activated, new OnExitActions(exitList));
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger.Add(pt);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger = [pt];
        }

        public void SetProximityTriggerArea(int index, string objName, string orSearch, string tSearch)
        {
            tSearch = $"{tSearch}{index:00}";
            ObjectReference or = GetObjectReference(objName, orSearch);
            int idIndex;
            idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger.FindIndex(o => o.Descr == tSearch);
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger[idIndex].Areas != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger[idIndex].Areas.ObjectReference.Add(or);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger[idIndex].Areas = new Areas([or]);
        }

        public void SetProximityTriggerOnEnterAction(int oIndex, string objName, string orSearch, int tIndex, string tSearch)
        {
            orSearch = $"{orSearch}{oIndex:00}";
            tSearch = $"{tSearch}{tIndex:00}";
            ObjectReference or = GetObjectReference(objName, orSearch);
            int idIndex;
            idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger.FindIndex(o => o.Descr == tSearch);
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger[idIndex].OnEnterActions != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger[idIndex].OnEnterActions.ObjectReference.Add(or);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionProximityTrigger[idIndex].OnEnterActions = new OnEnterActions([or]);
        }

        public void SetRealismOverrides()
        {
            SimMissionRealismOverrides ro = new()
            {
                Descr = "RealismOverrides",
                CrashBehavior = "UserSpecified",
                ATCMenuDisabled = "False",
                FlightRealism = "UserSpecified",
                WorldRealism = "UserSpecified",
                AircraftLabels = "UserSpecified",
                AvatarNoCollision = "UserSpecified",
                UnlimitedFuel = "UserSpecified"
            };
            _simBaseDocumentXML.WorldBaseFlight.SimMissionRealismOverrides = ro;
        }

        public void SetRectangleArea(string descr, string orientation, string length, string width, string height)
        {
            SimMissionRectangleArea ra = new(descr, orientation, length, width, height, new AttachedWorldPosition(), GetGUID());
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionRectangleArea != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionRectangleArea.Add(ra);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionRectangleArea = [ra];
        }

        public void SetScenarioMetadata(ScenarioFormData formData, Overview overview)
        {
            SimMissionUIScenarioMetadata md = new()
            {
                InstanceId = GetGUID(),
                SkillLevel = overview.Difficulty,
                LocationDescr = $"{formData.DestinationRunway.IcaoName} ({formData.DestinationRunway.IcaoId}) {formData.DestinationRunway.City}, {formData.DestinationRunway.Country}",
                DifficultyLevel = 1,
                EstimatedTime = ScenarioHTML.GetDuration(overview),
                UncompletedImage = "images\\imgM_i.bmp",
                CompletedImage = "images\\imgM_c.bmp",
                MissionBrief = "Overview.htm",
                AbbreviatedMissionBrief = $"{formData.ScenarioTitle}.htm",
                SuccessMessage = $"Success! You completed the \"{formData.ScenarioImageFolder}\" scenario objectives.",
                FailureMessage = $"Better luck next time! You failed to complete the \"{formData.ScenarioImageFolder}\" scenario objectives.",
                UserCrashMessage = $"Yikes! You crashed and therefore failed the \"{formData.ScenarioImageFolder}\" scenario objectives."
            };
            _simBaseDocumentXML.WorldBaseFlight.SimMissionUIScenarioMetadata = md;
        }

        public void SetScenarioVariable(string descr, string name, string value)
        {
            TriggerCondition tc = new()
            {
                Actions = [],
                TriggerValue = new()
            };
			SimMissionScenarioVariable sv = new([tc], GetGUID(), "", descr, name, value);
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionScenarioVariable != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionScenarioVariable.Add(sv);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionScenarioVariable = [sv];
        }

        public void SetScenarioVariableAction(string objName, string orSearch, int tcIndex, string tSearch)
        {
			ObjectReference or = GetObjectReference(objName, orSearch);
            List<ObjectReference> orList = [or];
            Actions a = new(orList);
            List<Actions> aList = [a];
            int idIndex;
            idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionScenarioVariable.FindIndex(o => o.Descr == tSearch);
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionScenarioVariable[idIndex].TriggerCondition[tcIndex].Actions.Count != 0)
				_simBaseDocumentXML.WorldBaseFlight.SimMissionScenarioVariable[idIndex].TriggerCondition[tcIndex].Actions[0].ObjectReference.Add(or);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionScenarioVariable[idIndex].TriggerCondition[tcIndex].Actions = aList;
        }

        public void SetScenarioVariableTriggerValue(double value, int tcIndex, string tSearch)
        {
            Constant constant = new(value);
            TriggerValue tv = new(constant);
            int idIndex;
            idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionScenarioVariable.FindIndex(o => o.Descr == tSearch);
            if (value == 0) // reset trigger value to NULL
                _simBaseDocumentXML.WorldBaseFlight.SimMissionScenarioVariable[idIndex].TriggerCondition = null;
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionScenarioVariable[idIndex].TriggerCondition[tcIndex].TriggerValue = tv;
        }

        public void SetScriptActions(string[] scripts)
        {
            List<SimMissionScriptAction> saList = [];

            for (int index = 0; index < scripts.Length; index++)
            {
                // Use an interpolated string with math for the ID
                string actionName = $"ScriptAction{index + 1:D2}";

                saList.Add(new SimMissionScriptAction(
                    actionName,
                    scripts[index],
                    GetGUID(),
                    ""
                ));
            }

            _simBaseDocumentXML.WorldBaseFlight.SimMissionScriptAction = saList;
        }

        public void SetTimerTrigger(string descr, double stopTime, string timer, string activated)
        {
            List<ObjectReference> orList = [];
            SimMissionTimerTrigger tt = new(descr, stopTime, timer, activated, GetGUID(), new Actions(orList));
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionTimerTrigger != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionTimerTrigger.Add(tt);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionTimerTrigger = [tt];
        }

		public void SetTimerTriggerAction(string objName, string orSearch, string tSearch)
		{
            ObjectReference or = GetObjectReference(objName, orSearch);
            int idIndex;
            idIndex = _simBaseDocumentXML.WorldBaseFlight.SimMissionTimerTrigger.FindIndex(o => o.Descr == tSearch);
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionTimerTrigger[idIndex].Actions != null)
				_simBaseDocumentXML.WorldBaseFlight.SimMissionTimerTrigger[idIndex].Actions.ObjectReference.Add(or);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionTimerTrigger[idIndex].Actions = new Actions([or]);
        }

        public void SetUIPanelWindow(int index, string descr, string locked, string mouseI, string panel, string docked, string keyboardI)
        {
            descr = $"{descr}{index:00}";
            SimMissionUIPanelWindow upw = new(descr, locked, mouseI, GetGUID(), panel, docked, keyboardI);
            if (_simBaseDocumentXML.WorldBaseFlight.SimMissionUIPanelWindow != null)
                _simBaseDocumentXML.WorldBaseFlight.SimMissionUIPanelWindow.Add(upw);
            else
                _simBaseDocumentXML.WorldBaseFlight.SimMissionUIPanelWindow = [upw];
        }

        #endregion
    }

    #region Simbase.Document class definitions

    [XmlRoot(ElementName = "Actions")]
	public class Actions
	{
		public Actions(List<ObjectReference> v1)
		{
			ObjectReference = v1;
		}

		public Actions()
		{
		}

		[XmlElement(ElementName = "ObjectReference")]
		public List<ObjectReference> ObjectReference { get; set; }
	}

	[XmlRoot(ElementName = "And")]
	public class And
	{

		[XmlElement(ElementName = "GreaterOrEqual")]
		public GreaterOrEqual GreaterOrEqual { get; set; }

		[XmlElement(ElementName = "GreaterThan")]
		public GreaterThan GreaterThan { get; set; }
	}

	[XmlRoot(ElementName = "Areas")]
	public class Areas
	{
		public Areas(List<ObjectReference> v1)
		{
			ObjectReference = v1;
		}

		public Areas()
		{
		}

		[XmlElement(ElementName = "ObjectReference")]
		public List<ObjectReference> ObjectReference { get; set; }
	}

	[XmlRoot(ElementName = "AttachedWorldObject")]
	public class AttachedWorldObject
    {
        public AttachedWorldObject(ObjectReference v1, string v2)
        {
            ObjectReference = v1;
			OffsetXYZ = v2;
        }

        public AttachedWorldObject()
        {
        }

        [XmlElement(ElementName = "ObjectReference")]
		public ObjectReference ObjectReference { get; set; }

		[XmlElement(ElementName = "OffsetXYZ")]
		public string OffsetXYZ { get; set; }
	}

	[XmlRoot(ElementName = "AttachedWorldPosition")]
	public class AttachedWorldPosition
	{
		public AttachedWorldPosition(string v1, string v2)
		{
			WorldPosition = v1;
			AltitudeIsAGL = v2;
		}
		public AttachedWorldPosition()
		{
		}

		[XmlElement(ElementName = "WorldPosition")]
		public string WorldPosition { get; set; }

		[XmlElement(ElementName = "AltitudeIsAGL")]
		public string AltitudeIsAGL { get; set; }
	}

	[XmlRoot(ElementName = "Condition")]
	public class Condition
	{

		[XmlElement(ElementName = "And")]
		public And And { get; set; }
	}

	[XmlRoot(ElementName = "Constant")]
	public class Constant
    {
        public Constant(double v1)
        {
            Double = v1;
        }
        public Constant()
        {
        }

        [XmlElement(ElementName = "Double")]
		public double Double { get; set; }
	}

	[XmlRoot(ElementName = "Goals")]
	public class Goals
	{
		public Goals(List<ObjectReference> v1)
		{
			ObjectReference = v1;
		}
		public Goals()
		{
		}

		[XmlElement(ElementName = "ObjectReference")]
		public List<ObjectReference> ObjectReference { get; set; }
	}

	[XmlRoot(ElementName = "GreaterOrEqual")]
	public class GreaterOrEqual
	{

		[XmlElement(ElementName = "LHS")]
		public LHS LHS { get; set; }

		[XmlElement(ElementName = "RHS")]
		public RHS RHS { get; set; }
	}

	[XmlRoot(ElementName = "GreaterThan")]
	public class GreaterThan
	{

		[XmlElement(ElementName = "LHS")]
		public LHS LHS { get; set; }

		[XmlElement(ElementName = "RHS")]
		public RHS RHS { get; set; }
	}

	[XmlRoot(ElementName = "GroundVehicleAI")]
	public class GroundVehicleAI
	{

		[XmlElement(ElementName = "GroundCruiseSpeed")]
		public double GroundCruiseSpeed { get; set; }

		[XmlElement(ElementName = "GroundTurnSpeed")]
		public double GroundTurnSpeed { get; set; }

		[XmlElement(ElementName = "GroundTurnTime")]
		public double GroundTurnTime { get; set; }

		[XmlElement(ElementName = "YieldToUser")]
		public string YieldToUser { get; set; }

		[XmlElement(ElementName = "WaypointListReference")]
		public string WaypointListReference { get; set; }

		[XmlElement(ElementName = "Unit_Mode")]
		public string UnitMode { get; set; }
	}

	[XmlRoot(ElementName = "LHS")]
	public class LHS
	{

		[XmlElement(ElementName = "Property")]
		public PropertyXML PropertyXML { get; set; }
	}

	[XmlRoot(ElementName = "ObjectReference")]
	public class ObjectReference
	{
		public ObjectReference(string v1)
		{
			InstanceId = v1;
		}

		public ObjectReference()
		{
		}

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }
	}

	[XmlRoot(ElementName = "ObjectReferenceList")]
	public class ObjectReferenceList
	{
		public ObjectReferenceList(List<ObjectReference> v1)
		{
			ObjectReference = v1;
		}

		public ObjectReferenceList()
		{
		}

		[XmlElement(ElementName = "ObjectReference")]
		public List<ObjectReference> ObjectReference { get; set; }
	}

	[XmlRoot(ElementName = "OnEnterActions")]
	public class OnEnterActions
	{
		public OnEnterActions(List<ObjectReference> v1)
		{
			ObjectReference = v1;
		}

		public OnEnterActions()
		{
		}

		[XmlElement(ElementName = "ObjectReference")]
		public List<ObjectReference> ObjectReference { get; set; }
	}

	[XmlRoot(ElementName = "OnExitActions")]
	public class OnExitActions
    {
        public OnExitActions(List<ObjectReference> v1)
        {
            ObjectReference = v1;
        }

        public OnExitActions()
        {
        }

        [XmlElement(ElementName = "ObjectReference")]
		public List<ObjectReference> ObjectReference { get; set; }
	}

	[XmlRoot(ElementName = "Property")]
	public class PropertyXML
	{

		[XmlElement(ElementName = "Name")]
		public string Name { get; set; }

		[XmlElement(ElementName = "Units")]
		public string Units { get; set; }

		[XmlElement(ElementName = "ObjectReference")]
		public ObjectReference ObjectReference { get; set; }
	}

	[XmlRoot(ElementName = "RHS")]
	public class RHS
	{

		[XmlElement(ElementName = "Constant")]
		public Constant Constant { get; set; }
    }

    [XmlRoot(ElementName = "SetWindowLocation")]
    public class SetWindowLocation
    {
        public SetWindowLocation(string v1, string v2)
        {
            LocationX = v1;
            LocationY = v2;
        }
        public SetWindowLocation()
        {
        }

        [XmlElement(ElementName = "LocationX")]
        public string LocationX { get; set; }

        [XmlElement(ElementName = "LocationY")]
        public string LocationY { get; set; }
    }

    [XmlRoot(ElementName = "SetWindowSize")]
	public class SetWindowSize
	{
		public SetWindowSize(string v1, string v2)
		{
			WindowWidth = v1;
			WindowHeight = v2;
		}
		public SetWindowSize()
		{
		}

		[XmlElement(ElementName = "WindowWidth")]
		public string WindowWidth { get; set; }

		[XmlElement(ElementName = "WindowHeight")]
		public string WindowHeight { get; set; }
	}

	[XmlRoot(ElementName = "Waypoint")]
	public class Waypoint
	{

		[XmlElement(ElementName = "AltitudeIsAGL")]
		public string AltitudeIsAGL { get; set; }

		[XmlElement(ElementName = "WorldPosition")]
		public string WorldPosition { get; set; }

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "WaypointID")]
		public int WaypointID { get; set; }

		[XmlElement(ElementName = "Orientation")]
		public string Orientation { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlElement(ElementName = "SpeedKnots")]
		public double SpeedKnots { get; set; }
	}

	[XmlRoot(ElementName = "SceneryObjects.LibraryObject")]
	public class SceneryObjectsLibraryObject
	{
		public SceneryObjectsLibraryObject(string v1, string v2, string v3, string v4, string v5, string v6, string v7, string v8)
		{
			Descr = v1;
			MDLGuid = v2;
			WorldPosition = v3;
			Orientation = v4;
			AltitudeIsAGL = v5;
			Scale = v6;
			InstanceId = v7;
			Activated = v8;
		}

		public SceneryObjectsLibraryObject()
		{
		}

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "MDLGuid")]
		public string MDLGuid { get; set; }

		[XmlElement(ElementName = "WorldPosition")]
		public string WorldPosition { get; set; }

		[XmlElement(ElementName = "Orientation")]
		public string Orientation { get; set; }

		[XmlElement(ElementName = "AltitudeIsAGL")]
		public string AltitudeIsAGL { get; set; }

		[XmlElement(ElementName = "Scale")]
		public string Scale { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlElement(ElementName = "Activated")]
		public string Activated { get; set; }
	}

	[XmlRoot(ElementName = "SimBase.Document")]
	public class SimBaseDocumentXML
	{

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "Title")]
		public string Title { get; set; }

		[XmlElement(ElementName = "WorldBase.Flight")]
		public WorldBaseFlight WorldBaseFlight { get; set; }

		[XmlElement(ElementName = "MissionBuilder.MissionBuilder")]
		public object MissionBuilderMissionBuilder { get; set; }

		[XmlElement(ElementName = "WorldBase.AreasOfInterest")]
		public object WorldBaseAreasOfInterest { get; set; }

		[XmlElement(ElementName = "WorldBase.Waypoints")]
		public WorldBaseWaypoints WorldBaseWaypoints { get; set; }

		[XmlAttribute(AttributeName = "Type")]
		public string Type { get; set; }

		[XmlAttribute(AttributeName = "version")]
		public double Version { get; set; }
	}

	[XmlRoot(ElementName = "SimContain.Container")]
	public class SimContainContainer
	{

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "WorldPosition")]
		public string WorldPosition { get; set; }

		[XmlElement(ElementName = "Orientation")]
		public string Orientation { get; set; }

		[XmlElement(ElementName = "ContainerTitle")]
		public string ContainerTitle { get; set; }

		[XmlElement(ElementName = "ContainerID")]
		public int ContainerID { get; set; }

		[XmlElement(ElementName = "IdentificationNumber")]
		public int IdentificationNumber { get; set; }

		[XmlElement(ElementName = "IsOnGround")]
		public string IsOnGround { get; set; }

		[XmlElement(ElementName = "AIType")]
		public string AIType { get; set; }

		[XmlElement(ElementName = "GroundVehicleAI")]
		public GroundVehicleAI GroundVehicleAI { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }
	}

	[XmlRoot(ElementName = "SimContain.WaypointList")]
	public class SimContainWaypointList
	{

		[XmlElement(ElementName = "WrapWaypoints")]
		public string WrapWaypoints { get; set; }

		[XmlElement(ElementName = "CurrentWaypoint")]
		public int CurrentWaypoint { get; set; }

		[XmlElement(ElementName = "BackupToFirst")]
		public string BackupToFirst { get; set; }

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "Waypoint")]
		public List<Waypoint> Waypoint { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.AirportLandingTrigger")]
	public class SimMissionAirportLandingTrigger
    {
        public SimMissionAirportLandingTrigger(string v1, string v2, string v3, Actions v4, string v5, string v6, RunwayFilter v7)
        {
            Descr = v1;
            LandingType = v2;
            Activated = v3;
            Actions = v4;
            InstanceId = v5;
            AirportIdent = v6;
            RunwayFilter = v7;
        }

        public SimMissionAirportLandingTrigger()
        {
        }
	
		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "LandingType")]
		public string LandingType { get; set; }

		[XmlElement(ElementName = "Activated")]
		public string Activated { get; set; }

		[XmlElement(ElementName = "Actions")]
		public Actions Actions { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlElement(ElementName = "AirportIdent")]
		public string AirportIdent { get; set; }

		[XmlElement(ElementName = "RunwayFilter")]
		public RunwayFilter RunwayFilter { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.AreaLandingTrigger")]
	public class SimMissionAreaLandingTrigger
	{

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "LandingType")]
		public string LandingType { get; set; }

		[XmlElement(ElementName = "Activated")]
		public string Activated { get; set; }

		[XmlElement(ElementName = "Actions")]
		public Actions Actions { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlElement(ElementName = "Areas")]
		public Areas Areas { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.CloseWindowAction")]
	public class SimMissionCloseWindowAction
	{
		public SimMissionCloseWindowAction(string v1, ObjectReference v2, string v3)
		{
			Descr = v1;
			ObjectReference = v2;
			InstanceId = v3;
		}

		public SimMissionCloseWindowAction()
		{
		}

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "ObjectReference")]
		public ObjectReference ObjectReference { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.CylinderArea")]
	public class SimMissionCylinderArea
	{
		public SimMissionCylinderArea(string v1, string v2, string v3, string v4, string v5, AttachedWorldPosition v6, string v7)
		{
			Descr = v1;
			Orientation = v2;
			AreaRadius = v3;
			Height = v4;
			DrawStyle = v5;
			AttachedWorldPosition = v6;
			InstanceId = v7;
		}

		public SimMissionCylinderArea()
		{
		}

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "Orientation")]
		public string Orientation { get; set; }

		[XmlElement(ElementName = "AreaRadius")]
		public string AreaRadius { get; set; }

		[XmlElement(ElementName = "Height")]
		public string Height { get; set; }

		[XmlElement(ElementName = "DrawStyle")]
		public string DrawStyle { get; set; }

		[XmlElement(ElementName = "AttachedWorldPosition")]
		public AttachedWorldPosition AttachedWorldPosition { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.DialogAction")]
	public class SimMissionDialogAction
	{
		public SimMissionDialogAction(string v1, string v2, string v3, string v4, string v5)
		{
			Descr = v1;
			Text = v2;
			DelaySeconds = v3;
			SoundType = v4;
			InstanceId = v5;
		}
		public SimMissionDialogAction()
		{
		}

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "Text")]
		public string Text { get; set; }

		[XmlElement(ElementName = "DelaySeconds")]
		public string DelaySeconds { get; set; }

		[XmlElement(ElementName = "SoundType")]
		public string SoundType { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.Goal")]
	public class SimMissionGoal
	{
		public SimMissionGoal(string v1, string v2, string v3)
		{
			Descr = v1;
			Text = v2;
			InstanceId = v3;
		}

		public SimMissionGoal()
		{
		}

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "Text")]
		public string Text { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.GoalResolutionAction")]
	public class SimMissionGoalResolutionAction
    {
        public SimMissionGoalResolutionAction(string v1, string v2, Goals v3, string v4)
        {
            GoalResolution = v1;
            Descr = v2;
            Goals = v3;
            InstanceId = v4;
        }

        public SimMissionGoalResolutionAction()
        {
        }

        [XmlElement(ElementName = "GoalResolution")]
		public string GoalResolution { get; set; }

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "Goals")]
		public Goals Goals { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.ObjectActivationAction")]
	public class SimMissionObjectActivationAction
    {
        public SimMissionObjectActivationAction(string v1, ObjectReferenceList v2, string v3, string v4)
        {
            Descr = v1;
            ObjectReferenceList = v2;
            InstanceId = v3;
            NewObjectState = v4;
        }

        public SimMissionObjectActivationAction()
        {
        }

        [XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "ObjectReferenceList")]
		public ObjectReferenceList ObjectReferenceList { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlElement(ElementName = "NewObjectState")]
		public string NewObjectState { get; set; }

	}

	[XmlRoot(ElementName = "SimMission.OneShotSoundAction")]
	public class SimMissionOneShotSoundAction
	{
        public SimMissionOneShotSoundAction(string v1, string v2, string v3)
        {
			Descr = v1;
			SoundFileName = v2;
			InstanceId = v3;
		}
		public SimMissionOneShotSoundAction()
		{
		}

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "SoundFileName")]
		public string SoundFileName { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }
    }

    [XmlRoot(ElementName = "SimMission.OnScreenText")]
    public class SimMissionOnScreenText
    {
        public SimMissionOnScreenText(string v1, string v2, string v3, string v4, string v5, string v6, string v7)
        {
            Descr = v1;
            Text = v2;
            OnScreenTextDisplayLocation = v3;
            RGBColor = v4;
            Activated = v5;
            OnScreenTextBackgroundColor = v6;
            InstanceId = v7;
        }

        public SimMissionOnScreenText()
        {
        }

        [XmlElement(ElementName = "Descr")]
        public string Descr { get; set; }

        [XmlElement(ElementName = "Text")]
        public string Text { get; set; }

        [XmlElement(ElementName = "OnScreenTextDisplayLocation")]
        public string OnScreenTextDisplayLocation { get; set; }

        [XmlElement(ElementName = "RGBColor")]
        public string RGBColor { get; set; }

        [XmlElement(ElementName = "Activated")]
        public string Activated { get; set; }

        [XmlElement(ElementName = "OnScreenTextBackgroundColor")]
        public string OnScreenTextBackgroundColor { get; set; }

        [XmlAttribute(AttributeName = "InstanceId")]
        public string InstanceId { get; set; }
    }

    [XmlRoot(ElementName = "SimMission.OpenWindowAction")]
	public class SimMissionOpenWindowAction
	{
		public SimMissionOpenWindowAction(string v1, SetWindowSize v2, SetWindowLocation v3, string v4, ObjectReference v5, string v6)
		{
			Descr = v1;
			SetWindowSize = v2;
            SetWindowLocation = v3;
            RelativeTo = v4;
			ObjectReference = v5;
			InstanceId = v6;
		}

		public SimMissionOpenWindowAction()
		{
		}

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "SetWindowSize")]
		public SetWindowSize SetWindowSize { get; set; }

        [XmlElement(ElementName = "SetWindowLocation")]
        public SetWindowLocation SetWindowLocation { get; set; }

        [XmlElement(ElementName = "RelativeTo")]
        public string RelativeTo { get; set; }

        [XmlElement(ElementName = "ObjectReference")]
		public ObjectReference ObjectReference { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.PointOfInterestActivationAction")]
	public class SimMissionPointOfInterestActivationAction
    {
        public SimMissionPointOfInterestActivationAction(string v1, ObjectReferenceList v2, string v3, string v4)
        {
            Descr = v1;
            ObjectReferenceList = v2;
            InstanceId = v3;
            NewObjectState = v4;
        }

        public SimMissionPointOfInterestActivationAction()
        {
        }

        [XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "ObjectReferenceList")]
		public ObjectReferenceList ObjectReferenceList { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlElement(ElementName = "NewObjectState")]
		public string NewObjectState { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.RectangleArea")]
	public class SimMissionRectangleArea
	{
		public SimMissionRectangleArea(string v1, string v2, string v3, string v4, string v5, AttachedWorldPosition v6, string v7)
		{
			Descr = v1;
			Orientation = v2;
			Length = v3;
			Width = v4;
			Height = v5;
			AttachedWorldPosition = v6;
			InstanceId = v7;
		}

		public SimMissionRectangleArea()
		{
		}

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "Orientation")]
		public string Orientation { get; set; }

		[XmlElement(ElementName = "Length")]
		public string Length { get; set; }

		[XmlElement(ElementName = "Width")]
		public string Width { get; set; }

		[XmlElement(ElementName = "Height")]
		public string Height { get; set; }

		[XmlElement(ElementName = "AttachedWorldPosition")]
		public AttachedWorldPosition AttachedWorldPosition { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlElement(ElementName = "AttachedWorldObject")]
		public AttachedWorldObject AttachedWorldObject { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.RunwayFilter")]
	public class RunwayFilter
	{
		public RunwayFilter(string v1, string v2)
		{
			RunwayNumber = v1;
			RunwayDesignator = v2;
		}

		public RunwayFilter()
		{
		}

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "RunwayNumber")]
		public string RunwayNumber { get; set; }

		[XmlElement(ElementName = "RunwayDesignator")]
		public string RunwayDesignator { get; set; }
    }

    [XmlRoot(ElementName = "SimMission.UIPanelWindow")]
    public class SimMissionUIPanelWindow
    {
        public SimMissionUIPanelWindow(string v1, string v2, string v3, string v4, string v5, string v6, string v7)
        {
            Descr = v1;
            Locked = v2;
            HasMouseInteractivity = v3;
            InstanceId = v4;
            UIPanelFileName = v5;
            Docked = v6;
            HasKeyboardInteractivity = v7;
        }

        public SimMissionUIPanelWindow()
        {
        }

        [XmlElement(ElementName = "Descr")]
        public string Descr { get; set; }

        [XmlElement(ElementName = "Locked")]
        public string Locked { get; set; }

        [XmlElement(ElementName = "HasMouseInteractivity")]
        public string HasMouseInteractivity { get; set; }

        [XmlElement(ElementName = "FlashFileName")]
        public string FlashFileName { get; set; }

        [XmlAttribute(AttributeName = "InstanceId")]
        public string InstanceId { get; set; }

        [XmlElement(ElementName = "UIPanelFileName")]
        public string UIPanelFileName { get; set; }

        [XmlElement(ElementName = "Docked")]
        public string Docked { get; set; }

        [XmlElement(ElementName = "HasKeyboardInteractivity")]
        public string HasKeyboardInteractivity { get; set; }
    }

    [XmlRoot(ElementName = "SimMission.ScaleformPanelWindow")]
	public class SimMissionScaleformPanelWindow
	{
		public SimMissionScaleformPanelWindow(string v1, string v2, string v3, string v4, string v5, string v6, string v7, string v8)
		{
			Descr = v1;
			Locked = v2;
			HasMouseInteractivity = v3;
			FlashFileName = v4;
			InstanceId = v5;
			UIPanelFileName = v6;
			Docked = v7;
			HasKeyboardInteractivity = v8;
		}

		public SimMissionScaleformPanelWindow()
		{
		}

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "Locked")]
		public string Locked { get; set; }

		[XmlElement(ElementName = "HasMouseInteractivity")]
		public string HasMouseInteractivity { get; set; }

		[XmlElement(ElementName = "FlashFileName")]
		public string FlashFileName { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlElement(ElementName = "UIPanelFileName")]
		public string UIPanelFileName { get; set; }

		[XmlElement(ElementName = "Docked")]
		public string Docked { get; set; }

		[XmlElement(ElementName = "HasKeyboardInteractivity")]
		public string HasKeyboardInteractivity { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.PointOfInterest")]
	public class SimMissionPointOfInterest
	{
		public SimMissionPointOfInterest(string v1, string v2, string v3, AttachedWorldObject v4, string v5, string v6, int v7)
		{
			Descr = v1;
			TargetName = v2;
			CurrentSelection = v3;
			AttachedWorldObject = v4;
			InstanceId = v5;
			Activated = v6;
			CycleOrder = v7;
		}

		public SimMissionPointOfInterest()
		{
		}

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "TargetName")]
		public string TargetName { get; set; }

		[XmlElement(ElementName = "CurrentSelection")]
		public string CurrentSelection { get; set; }

		[XmlElement(ElementName = "AttachedWorldObject")]
		public AttachedWorldObject AttachedWorldObject { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlElement(ElementName = "Activated")]
		public string Activated { get; set; }

		[XmlElement(ElementName = "CycleOrder")]
		public int CycleOrder { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.PropertyTrigger")]
	public class SimMissionPropertyTrigger
	{

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "Activated")]
		public string Activated { get; set; }

		[XmlElement(ElementName = "Actions")]
		public Actions Actions { get; set; }

		[XmlElement(ElementName = "Condition")]
		public Condition Condition { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.ProximityTrigger")]
	public class SimMissionProximityTrigger
    {
        public SimMissionProximityTrigger(string v1, Areas v2, OnEnterActions v3, string v4, string v5, OnExitActions v6)
        {
            Descr = v1;
            Areas = v2;
            OnEnterActions = v3;
            InstanceId = v4;
            Activated = v5;
            OnExitActions = v6;
        }

        public SimMissionProximityTrigger()
        {
        }

        [XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "Areas")]
		public Areas Areas { get; set; }

		[XmlElement(ElementName = "OnEnterActions")]
		public OnEnterActions OnEnterActions { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlElement(ElementName = "Activated")]
		public string Activated { get; set; }

		[XmlElement(ElementName = "OnExitActions")]
		public OnExitActions OnExitActions { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.RealismOverrides")]
	public class SimMissionRealismOverrides
	{

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "UserTips")]
		public string UserTips { get; set; }

		[XmlElement(ElementName = "CrashBehavior")]
		public string CrashBehavior { get; set; }

		[XmlElement(ElementName = "ATCMenuDisabled")]
		public string ATCMenuDisabled { get; set; }

		[XmlElement(ElementName = "FlightRealism")]
		public string FlightRealism { get; set; }

		[XmlElement(ElementName = "WorldRealism")]
		public string WorldRealism { get; set; }

		[XmlElement(ElementName = "UnlimitedFuel")]
		public string UnlimitedFuel { get; set; }

		[XmlElement(ElementName = "AircraftLabels")]
		public string AircraftLabels { get; set; }

		[XmlElement(ElementName = "AvatarNoCollision")]
		public string AvatarNoCollision { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.TimerTrigger")]
	public class SimMissionTimerTrigger
    {
        public SimMissionTimerTrigger(string v1, double v2, string v3, string v4, string v5, Actions v6)
        {
            Descr = v1;
            StopTime = v2;
            OnScreenTimer = v3;
            Activated = v4;
            InstanceId = v5;
            Actions = v6;
        }

        public SimMissionTimerTrigger()
        {
        }

        [XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "StopTime")]
		public double StopTime { get; set; }

		[XmlElement(ElementName = "OnScreenTimer")]
		public string OnScreenTimer { get; set; }

		[XmlElement(ElementName = "Activated")]
		public string Activated { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlElement(ElementName = "Actions")]
		public Actions Actions { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.ScenarioVariable")]
	public class SimMissionScenarioVariable
	{
		public SimMissionScenarioVariable(List<TriggerCondition> v1, string v2, string v3, string v4, string v5, string v6)
		{
			TriggerCondition = v1;
			InstanceId = v2;
			Text = v3;
			Descr = v4;
			Name = v5;
			VariableValue = v6;
		}

		public SimMissionScenarioVariable()
		{
		}

		[XmlElement(ElementName = "TriggerCondition")]
		public List<TriggerCondition> TriggerCondition { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlText]
		public string Text { get; set; }

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "Name")]
		public string Name { get; set; }

		[XmlElement(ElementName = "VariableValue")]
		public string VariableValue { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.ScriptAction")]
	public class SimMissionScriptAction
	{
		public SimMissionScriptAction(string v1, string v2, string v3, string v4)
		{
			Descr = v1;
			Script = v2;
			InstanceId = v3;
			Text = v4;
		}

		public SimMissionScriptAction()
		{
		}

		[XmlElement(ElementName = "Descr")]
		public string Descr { get; set; }

		[XmlElement(ElementName = "Script")]
		public string Script { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }

		[XmlText]
		public string Text { get; set; }
	}

	[XmlRoot(ElementName = "SimMissionUI.ScenarioMetadata")]
	public class SimMissionUIScenarioMetadata
	{
		[XmlElement(ElementName = "SkillLevel")]
		public string SkillLevel { get; set; }

		[XmlElement(ElementName = "LocationDescr")]
		public string LocationDescr { get; set; }

		[XmlElement(ElementName = "DifficultyLevel")]
		public int DifficultyLevel { get; set; }

		[XmlElement(ElementName = "EstimatedTime")]
		public int EstimatedTime { get; set; }

		[XmlElement(ElementName = "UncompletedImage")]
		public string UncompletedImage { get; set; }	

		[XmlElement(ElementName = "CompletedImage")]
		public string CompletedImage { get; set; }

		[XmlElement(ElementName = "ExitMissionImage")]
		public string ExitMissionImage { get; set; }

		[XmlElement(ElementName = "MissionBrief")]
		public string MissionBrief { get; set; }

		[XmlElement(ElementName = "AbbreviatedMissionBrief")]
		public string AbbreviatedMissionBrief { get; set; }

		[XmlElement(ElementName = "SuccessMessage")]
		public string SuccessMessage { get; set; }

		[XmlElement(ElementName = "FailureMessage")]
		public string FailureMessage { get; set; }

		[XmlElement(ElementName = "UserCrashMessage")]
		public string UserCrashMessage { get; set; }

		[XmlAttribute(AttributeName = "InstanceId")]
		public string InstanceId { get; set; }
	}

	[XmlRoot(ElementName = "SimMission.DisabledTrafficAirports")]
	public class SimMissionDisabledTrafficAirports
	{
		public SimMissionDisabledTrafficAirports(string v1)
		{
			AirportIdent = v1;
		}

		public SimMissionDisabledTrafficAirports()
		{
		}

		[XmlElement(ElementName = "AirportIdent")]
		public string AirportIdent { get; set; }
	}

	[XmlRoot(ElementName = "TriggerCondition")]
	public class TriggerCondition
    {
        public TriggerCondition(List<Actions> v1, TriggerValue v2)
        {
            Actions = v1;
            TriggerValue = v2;
        }

        public TriggerCondition()
        {
        }

        [XmlElement(ElementName = "Actions")]
		public List<Actions> Actions { get; set; }

		[XmlElement(ElementName = "TriggerValue")]
		public TriggerValue TriggerValue { get; set; }
	}

	[XmlRoot(ElementName = "TriggerValue")]
	public class TriggerValue
    {
        public TriggerValue(Constant v1)
        {
            Constant = v1;
        }

        public TriggerValue()
        {
        }

        [XmlElement(ElementName = "Constant")]
		public Constant Constant { get; set; }
	}

	[XmlRoot(ElementName = "WorldBase.Flight")]
	public class WorldBaseFlight
	{

		[XmlElement(ElementName = "SimContain.Container")]
		public List<SimContainContainer> SimContainContainer { get; set; }

		[XmlElement(ElementName = "SceneryObjects.LibraryObject")]
		public List<SceneryObjectsLibraryObject> SceneryObjectsLibraryObject { get; set; }

		[XmlElement(ElementName = "SimMission.AirportLandingTrigger")]
		public List<SimMissionAirportLandingTrigger> SimMissionAirportLandingTrigger { get; set; }

		[XmlElement(ElementName = "SimMission.AreaLandingTrigger")]
		public List<SimMissionAreaLandingTrigger> SimMissionAreaLandingTrigger { get; set; }

		[XmlElement(ElementName = "SimMission.CloseWindowAction")]
		public List<SimMissionCloseWindowAction> SimMissionCloseWindowAction { get; set; }

		[XmlElement(ElementName = "SimMission.CylinderArea")]
		public List<SimMissionCylinderArea> SimMissionCylinderArea { get; set; }

		[XmlElement(ElementName = "SimMission.DialogAction")]
		public List<SimMissionDialogAction> SimMissionDialogAction { get; set; }

		[XmlElement(ElementName = "SimMission.DisabledTrafficAirports")]
		public SimMissionDisabledTrafficAirports SimMissionDisabledTrafficAirports { get; set; }

		[XmlElement(ElementName = "SimMission.Goal")]
		public List<SimMissionGoal> SimMissionGoal { get; set; }

		[XmlElement(ElementName = "SimMission.GoalResolutionAction")]
		public List<SimMissionGoalResolutionAction> SimMissionGoalResolutionAction { get; set; }

		[XmlElement(ElementName = "SimMission.ObjectActivationAction")]
		public List<SimMissionObjectActivationAction> SimMissionObjectActivationAction { get; set; }

        [XmlElement(ElementName = "SimMission.OneShotSoundAction")]
        public List<SimMissionOneShotSoundAction> SimMissionOneShotSoundAction { get; set; }

        [XmlElement(ElementName = "SimMission.OnScreenText")]
		public List<SimMissionOnScreenText> SimMissionOnScreenText { get; set; }

		[XmlElement(ElementName = "SimMission.OpenWindowAction")]
		public List<SimMissionOpenWindowAction> SimMissionOpenWindowAction { get; set; }

		[XmlElement(ElementName = "SimMission.PointOfInterest")]
		public List<SimMissionPointOfInterest> SimMissionPointOfInterest { get; set; }

		[XmlElement(ElementName = "SimMission.PointOfInterestActivationAction")]
		public List<SimMissionPointOfInterestActivationAction> SimMissionPointOfInterestActivationAction { get; set; }

		[XmlElement(ElementName = "SimMission.PropertyTrigger")]
		public List<SimMissionPropertyTrigger> SimMissionPropertyTrigger { get; set; }

		[XmlElement(ElementName = "SimMission.ProximityTrigger")]
		public List<SimMissionProximityTrigger> SimMissionProximityTrigger { get; set; }

		[XmlElement(ElementName = "SimMission.RealismOverrides")]
		public SimMissionRealismOverrides SimMissionRealismOverrides { get; set; }

		[XmlElement(ElementName = "SimMission.RectangleArea")]
		public List<SimMissionRectangleArea> SimMissionRectangleArea { get; set; }

		[XmlElement(ElementName = "SimMission.ScaleformPanelWindow")]
		public List<SimMissionScaleformPanelWindow> SimMissionScaleformPanelWindow { get; set; }

		[XmlElement(ElementName = "SimMission.ScenarioVariable")]
		public List<SimMissionScenarioVariable> SimMissionScenarioVariable { get; set; }

		[XmlElement(ElementName = "SimMission.ScriptAction")]
		public List<SimMissionScriptAction> SimMissionScriptAction { get; set; }

		[XmlElement(ElementName = "SimMission.TimerTrigger")]
		public List<SimMissionTimerTrigger> SimMissionTimerTrigger { get; set; }

		[XmlElement(ElementName = "SimMissionUI.ScenarioMetadata")]
		public SimMissionUIScenarioMetadata SimMissionUIScenarioMetadata { get; set; }

        [XmlElement(ElementName = "SimMission.UIPanelWindow")]
        public List<SimMissionUIPanelWindow> SimMissionUIPanelWindow { get; set; }
    }

	[XmlRoot(ElementName = "WorldBase.Waypoints")]
	public class WorldBaseWaypoints
	{

		[XmlElement(ElementName = "SimContain.WaypointList")]
		public List<SimContainWaypointList> SimContainWaypointList { get; set; }
	}

	#endregion
}
