//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3D_Scenario_Generator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSettingsCacheDate {
            get {
                return ((string)(this["TextBoxSettingsCacheDate"]));
            }
            set {
                this["TextBoxSettingsCacheDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSettingsCacheDailyTotal {
            get {
                return ((string)(this["TextBoxSettingsCacheDailyTotal"]));
            }
            set {
                this["TextBoxSettingsCacheDailyTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSettingsMapMonitorNumber {
            get {
                return ((string)(this["TextBoxSettingsMapMonitorNumber"]));
            }
            set {
                this["TextBoxSettingsMapMonitorNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSettingsMapOffset {
            get {
                return ((string)(this["TextBoxSettingsMapOffset"]));
            }
            set {
                this["TextBoxSettingsMapOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSettingsMapMonitorWidth {
            get {
                return ((string)(this["TextBoxSettingsMapMonitorWidth"]));
            }
            set {
                this["TextBoxSettingsMapMonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSettingsMapMonitorHeight {
            get {
                return ((string)(this["TextBoxSettingsMapMonitorHeight"]));
            }
            set {
                this["TextBoxSettingsMapMonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourPhotoMonitorNumber {
            get {
                return ((string)(this["TextBoxPhotoTourPhotoMonitorNumber"]));
            }
            set {
                this["TextBoxPhotoTourPhotoMonitorNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourPhotoOffset {
            get {
                return ((string)(this["TextBoxPhotoTourPhotoOffset"]));
            }
            set {
                this["TextBoxPhotoTourPhotoOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourPhotoMonitorWidth {
            get {
                return ((string)(this["TextBoxPhotoTourPhotoMonitorWidth"]));
            }
            set {
                this["TextBoxPhotoTourPhotoMonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourPhotoMonitorHeight {
            get {
                return ((string)(this["TextBoxPhotoTourPhotoMonitorHeight"]));
            }
            set {
                this["TextBoxPhotoTourPhotoMonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSettingsCacheUsage {
            get {
                return ((string)(this["TextBoxSettingsCacheUsage"]));
            }
            set {
                this["TextBoxSettingsCacheUsage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxSettingsScenarioFolder {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxSettingsScenarioFolder"]));
            }
            set {
                this["ComboBoxSettingsScenarioFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxSettingsScenarioFolderSelectedIndex {
            get {
                return ((int)(this["ComboBoxSettingsScenarioFolderSelectedIndex"]));
            }
            set {
                this["ComboBoxSettingsScenarioFolderSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxPhotoTourPhotoAlignmentSelectedIndex {
            get {
                return ((int)(this["ComboBoxPhotoTourPhotoAlignmentSelectedIndex"]));
            }
            set {
                this["ComboBoxPhotoTourPhotoAlignmentSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxSettingsMapAlignmentSelectedIndex {
            get {
                return ((int)(this["ComboBoxSettingsMapAlignmentSelectedIndex"]));
            }
            set {
                this["ComboBoxSettingsMapAlignmentSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxSettingsMapWindowSizeSelectedIndex {
            get {
                return ((int)(this["ComboBoxSettingsMapWindowSizeSelectedIndex"]));
            }
            set {
                this["ComboBoxSettingsMapWindowSizeSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourConstraintsHotspotRadius {
            get {
                return ((string)(this["TextBoxPhotoTourConstraintsHotspotRadius"]));
            }
            set {
                this["TextBoxPhotoTourConstraintsHotspotRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourConstraintsMinLegDist {
            get {
                return ((string)(this["TextBoxPhotoTourConstraintsMinLegDist"]));
            }
            set {
                this["TextBoxPhotoTourConstraintsMinLegDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourConstraintsMaxLegDist {
            get {
                return ((string)(this["TextBoxPhotoTourConstraintsMaxLegDist"]));
            }
            set {
                this["TextBoxPhotoTourConstraintsMaxLegDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourConstraintsMinNoLegs {
            get {
                return ((string)(this["TextBoxPhotoTourConstraintsMinNoLegs"]));
            }
            set {
                this["TextBoxPhotoTourConstraintsMinNoLegs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourConstraintsMaxNoLegs {
            get {
                return ((string)(this["TextBoxPhotoTourConstraintsMaxNoLegs"]));
            }
            set {
                this["TextBoxPhotoTourConstraintsMaxNoLegs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourConstraintsMaxBearingChange {
            get {
                return ((string)(this["TextBoxPhotoTourConstraintsMaxBearingChange"]));
            }
            set {
                this["TextBoxPhotoTourConstraintsMaxBearingChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxSettingsMapAlignment {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxSettingsMapAlignment"]));
            }
            set {
                this["ComboBoxSettingsMapAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxSettingsMapWindowSize {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxSettingsMapWindowSize"]));
            }
            set {
                this["ComboBoxSettingsMapWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxPhotoTourPhotoAlignment {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxPhotoTourPhotoAlignment"]));
            }
            set {
                this["ComboBoxPhotoTourPhotoAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitUpwind {
            get {
                return ((string)(this["TextBoxCircuitUpwind"]));
            }
            set {
                this["TextBoxCircuitUpwind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitBase {
            get {
                return ((string)(this["TextBoxCircuitBase"]));
            }
            set {
                this["TextBoxCircuitBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitFinal {
            get {
                return ((string)(this["TextBoxCircuitFinal"]));
            }
            set {
                this["TextBoxCircuitFinal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitHeightUpwind {
            get {
                return ((string)(this["TextBoxCircuitHeightUpwind"]));
            }
            set {
                this["TextBoxCircuitHeightUpwind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitHeightDown {
            get {
                return ((string)(this["TextBoxCircuitHeightDown"]));
            }
            set {
                this["TextBoxCircuitHeightDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitHeightBase {
            get {
                return ((string)(this["TextBoxCircuitHeightBase"]));
            }
            set {
                this["TextBoxCircuitHeightBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitTurnRate {
            get {
                return ((string)(this["TextBoxCircuitTurnRate"]));
            }
            set {
                this["TextBoxCircuitTurnRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitSpeed {
            get {
                return ((string)(this["TextBoxCircuitSpeed"]));
            }
            set {
                this["TextBoxCircuitSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignTilt {
            get {
                return ((string)(this["TextBoxSignTilt"]));
            }
            set {
                this["TextBoxSignTilt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignWindowWidth {
            get {
                return ((string)(this["TextBoxSignWindowWidth"]));
            }
            set {
                this["TextBoxSignWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignGateHeight {
            get {
                return ((string)(this["TextBoxSignGateHeight"]));
            }
            set {
                this["TextBoxSignGateHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignSegmentLength {
            get {
                return ((string)(this["TextBoxSignSegmentLength"]));
            }
            set {
                this["TextBoxSignSegmentLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignSegmentRadius {
            get {
                return ((string)(this["TextBoxSignSegmentRadius"]));
            }
            set {
                this["TextBoxSignSegmentRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCelestialMinDist {
            get {
                return ((string)(this["TextBoxCelestialMinDist"]));
            }
            set {
                this["TextBoxCelestialMinDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCelestialMaxDist {
            get {
                return ((string)(this["TextBoxCelestialMaxDist"]));
            }
            set {
                this["TextBoxCelestialMaxDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxSignMessage {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxSignMessage"]));
            }
            set {
                this["ComboBoxSignMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxSignMessageSelectedIndex {
            get {
                return ((int)(this["ComboBoxSignMessageSelectedIndex"]));
            }
            set {
                this["ComboBoxSignMessageSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignMonitorNumber {
            get {
                return ((string)(this["TextBoxSignMonitorNumber"]));
            }
            set {
                this["TextBoxSignMonitorNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignOffset {
            get {
                return ((string)(this["TextBoxSignOffset"]));
            }
            set {
                this["TextBoxSignOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxSignAlignment {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxSignAlignment"]));
            }
            set {
                this["ComboBoxSignAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxSignAlignmentSelectedIndex {
            get {
                return ((int)(this["ComboBoxSignAlignmentSelectedIndex"]));
            }
            set {
                this["ComboBoxSignAlignmentSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignMonitorWidth {
            get {
                return ((string)(this["TextBoxSignMonitorWidth"]));
            }
            set {
                this["TextBoxSignMonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignMonitorHeight {
            get {
                return ((string)(this["TextBoxSignMonitorHeight"]));
            }
            set {
                this["TextBoxSignMonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiURL {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiURL"]));
            }
            set {
                this["ComboBoxWikiURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiURLSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiURLSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiURLSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TextBoxWikiItemLinkColumn {
            get {
                return ((string)(this["TextBoxWikiItemLinkColumn"]));
            }
            set {
                this["TextBoxWikiItemLinkColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiDistance {
            get {
                return ((string)(this["TextBoxWikiDistance"]));
            }
            set {
                this["TextBoxWikiDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiStartingItem {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiStartingItem"]));
            }
            set {
                this["ComboBoxWikiStartingItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiStartingItemSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiStartingItemSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiStartingItemSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiFinishingItem {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiFinishingItem"]));
            }
            set {
                this["ComboBoxWikiFinishingItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiFinishingItemSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiFinishingItemSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiFinishingItemSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiTableNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiTableNames"]));
            }
            set {
                this["ComboBoxWikiTableNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiTableNamesSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiTableNamesSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiTableNamesSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiRoute {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiRoute"]));
            }
            set {
                this["ComboBoxWikiRoute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiRouteSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiRouteSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiRouteSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiURLMonitorNumber {
            get {
                return ((string)(this["TextBoxWikiURLMonitorNumber"]));
            }
            set {
                this["TextBoxWikiURLMonitorNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiURLOffset {
            get {
                return ((string)(this["TextBoxWikiURLOffset"]));
            }
            set {
                this["TextBoxWikiURLOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiURLAlignment {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiURLAlignment"]));
            }
            set {
                this["ComboBoxWikiURLAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiURLAlignmentSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiURLAlignmentSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiURLAlignmentSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiURLMonitorWidth {
            get {
                return ((string)(this["TextBoxWikiURLMonitorWidth"]));
            }
            set {
                this["TextBoxWikiURLMonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiURLMonitorHeight {
            get {
                return ((string)(this["TextBoxWikiURLMonitorHeight"]));
            }
            set {
                this["TextBoxWikiURLMonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiURLWindowHeight {
            get {
                return ((string)(this["TextBoxWikiURLWindowHeight"]));
            }
            set {
                this["TextBoxWikiURLWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiURLWindowWidth {
            get {
                return ((string)(this["TextBoxWikiURLWindowWidth"]));
            }
            set {
                this["TextBoxWikiURLWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxSettingsSimulatorVersion {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxSettingsSimulatorVersion"]));
            }
            set {
                this["ComboBoxSettingsSimulatorVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxSettingsSimulatorVersionSelectedIndex {
            get {
                return ((int)(this["ComboBoxSettingsSimulatorVersionSelectedIndex"]));
            }
            set {
                this["ComboBoxSettingsSimulatorVersionSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\Lockheed Martin\\Prepar3D v")]
        public string TextBoxSettingsP3DprogramData {
            get {
                return ((string)(this["TextBoxSettingsP3DprogramData"]));
            }
            set {
                this["TextBoxSettingsP3DprogramData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSettingsOSMServerAPIkey {
            get {
                return ((string)(this["TextBoxSettingsOSMServerAPIkey"]));
            }
            set {
                this["TextBoxSettingsOSMServerAPIkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourConstraintsMaxAttempts {
            get {
                return ((string)(this["TextBoxPhotoTourConstraintsMaxAttempts"]));
            }
            set {
                this["TextBoxPhotoTourConstraintsMaxAttempts"] = value;
            }
        }
    }
}
