//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3D_Scenario_Generator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection AircraftTitles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AircraftTitles"]));
            }
            set {
                this["AircraftTitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection AircraftImages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AircraftImages"]));
            }
            set {
                this["AircraftImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection AircraftCruiseSpeeds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AircraftCruiseSpeeds"]));
            }
            set {
                this["AircraftCruiseSpeeds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSettingsCacheDate {
            get {
                return ((string)(this["TextBoxSettingsCacheDate"]));
            }
            set {
                this["TextBoxSettingsCacheDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSettingsCacheDailyTotal {
            get {
                return ((string)(this["TextBoxSettingsCacheDailyTotal"]));
            }
            set {
                this["TextBoxSettingsCacheDailyTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourMapMonitorNumber {
            get {
                return ((string)(this["TextBoxPhotoTourMapMonitorNumber"]));
            }
            set {
                this["TextBoxPhotoTourMapMonitorNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourMapOffset {
            get {
                return ((string)(this["TextBoxPhotoTourMapOffset"]));
            }
            set {
                this["TextBoxPhotoTourMapOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourMapMonitorWidth {
            get {
                return ((string)(this["TextBoxPhotoTourMapMonitorWidth"]));
            }
            set {
                this["TextBoxPhotoTourMapMonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourMapMonitorHeight {
            get {
                return ((string)(this["TextBoxPhotoTourMapMonitorHeight"]));
            }
            set {
                this["TextBoxPhotoTourMapMonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourPhotoMonitorNumber {
            get {
                return ((string)(this["TextBoxPhotoTourPhotoMonitorNumber"]));
            }
            set {
                this["TextBoxPhotoTourPhotoMonitorNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourPhotoOffset {
            get {
                return ((string)(this["TextBoxPhotoTourPhotoOffset"]));
            }
            set {
                this["TextBoxPhotoTourPhotoOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourPhotoMonitorWidth {
            get {
                return ((string)(this["TextBoxPhotoTourPhotoMonitorWidth"]));
            }
            set {
                this["TextBoxPhotoTourPhotoMonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourPhotoMonitorHeight {
            get {
                return ((string)(this["TextBoxPhotoTourPhotoMonitorHeight"]));
            }
            set {
                this["TextBoxPhotoTourPhotoMonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxSettingsCacheServers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxSettingsCacheServers"]));
            }
            set {
                this["ComboBoxSettingsCacheServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSettingsCacheUsage {
            get {
                return ((string)(this["TextBoxSettingsCacheUsage"]));
            }
            set {
                this["TextBoxSettingsCacheUsage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxSettingsScenarioFolder {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxSettingsScenarioFolder"]));
            }
            set {
                this["ComboBoxSettingsScenarioFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxSettingsCacheServersSelectedIndex {
            get {
                return ((int)(this["ComboBoxSettingsCacheServersSelectedIndex"]));
            }
            set {
                this["ComboBoxSettingsCacheServersSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxSettingsScenarioFolderSelectedIndex {
            get {
                return ((int)(this["ComboBoxSettingsScenarioFolderSelectedIndex"]));
            }
            set {
                this["ComboBoxSettingsScenarioFolderSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxPhotoTourPhotoAlignmentSelectedIndex {
            get {
                return ((int)(this["ComboBoxPhotoTourPhotoAlignmentSelectedIndex"]));
            }
            set {
                this["ComboBoxPhotoTourPhotoAlignmentSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxPhotoTourMapAlignmentSelectedIndex {
            get {
                return ((int)(this["ComboBoxPhotoTourMapAlignmentSelectedIndex"]));
            }
            set {
                this["ComboBoxPhotoTourMapAlignmentSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxPhotoTourMapWindowSizeSelectedIndex {
            get {
                return ((int)(this["ComboBoxPhotoTourMapWindowSizeSelectedIndex"]));
            }
            set {
                this["ComboBoxPhotoTourMapWindowSizeSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourMapHotspotRadius {
            get {
                return ((string)(this["TextBoxPhotoTourMapHotspotRadius"]));
            }
            set {
                this["TextBoxPhotoTourMapHotspotRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourConstraintsMinLegDist {
            get {
                return ((string)(this["TextBoxPhotoTourConstraintsMinLegDist"]));
            }
            set {
                this["TextBoxPhotoTourConstraintsMinLegDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourConstraintsMaxLegDist {
            get {
                return ((string)(this["TextBoxPhotoTourConstraintsMaxLegDist"]));
            }
            set {
                this["TextBoxPhotoTourConstraintsMaxLegDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourConstraintsMinNoLegs {
            get {
                return ((string)(this["TextBoxPhotoTourConstraintsMinNoLegs"]));
            }
            set {
                this["TextBoxPhotoTourConstraintsMinNoLegs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourConstraintsMaxNoLegs {
            get {
                return ((string)(this["TextBoxPhotoTourConstraintsMaxNoLegs"]));
            }
            set {
                this["TextBoxPhotoTourConstraintsMaxNoLegs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxPhotoTourConstraintsMaxBearingChange {
            get {
                return ((string)(this["TextBoxPhotoTourConstraintsMaxBearingChange"]));
            }
            set {
                this["TextBoxPhotoTourConstraintsMaxBearingChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxPhotoTourMapAlignment {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxPhotoTourMapAlignment"]));
            }
            set {
                this["ComboBoxPhotoTourMapAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxPhotoTourMapWindowSize {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxPhotoTourMapWindowSize"]));
            }
            set {
                this["ComboBoxPhotoTourMapWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxPhotoTourPhotoAlignment {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxPhotoTourPhotoAlignment"]));
            }
            set {
                this["ComboBoxPhotoTourPhotoAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitUpwind {
            get {
                return ((string)(this["TextBoxCircuitUpwind"]));
            }
            set {
                this["TextBoxCircuitUpwind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitBase {
            get {
                return ((string)(this["TextBoxCircuitBase"]));
            }
            set {
                this["TextBoxCircuitBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitFinal {
            get {
                return ((string)(this["TextBoxCircuitFinal"]));
            }
            set {
                this["TextBoxCircuitFinal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitHeightUpwind {
            get {
                return ((string)(this["TextBoxCircuitHeightUpwind"]));
            }
            set {
                this["TextBoxCircuitHeightUpwind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitHeightDown {
            get {
                return ((string)(this["TextBoxCircuitHeightDown"]));
            }
            set {
                this["TextBoxCircuitHeightDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitHeightBase {
            get {
                return ((string)(this["TextBoxCircuitHeightBase"]));
            }
            set {
                this["TextBoxCircuitHeightBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitTurnRate {
            get {
                return ((string)(this["TextBoxCircuitTurnRate"]));
            }
            set {
                this["TextBoxCircuitTurnRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCircuitSpeed {
            get {
                return ((string)(this["TextBoxCircuitSpeed"]));
            }
            set {
                this["TextBoxCircuitSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignTilt {
            get {
                return ((string)(this["TextBoxSignTilt"]));
            }
            set {
                this["TextBoxSignTilt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignWindowWidth {
            get {
                return ((string)(this["TextBoxSignWindowWidth"]));
            }
            set {
                this["TextBoxSignWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignGateHeight {
            get {
                return ((string)(this["TextBoxSignGateHeight"]));
            }
            set {
                this["TextBoxSignGateHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignSegmentLength {
            get {
                return ((string)(this["TextBoxSignSegmentLength"]));
            }
            set {
                this["TextBoxSignSegmentLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignSegmentRadius {
            get {
                return ((string)(this["TextBoxSignSegmentRadius"]));
            }
            set {
                this["TextBoxSignSegmentRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCelestialMinDist {
            get {
                return ((string)(this["TextBoxCelestialMinDist"]));
            }
            set {
                this["TextBoxCelestialMinDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxCelestialMaxDist {
            get {
                return ((string)(this["TextBoxCelestialMaxDist"]));
            }
            set {
                this["TextBoxCelestialMaxDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxSignMessage {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxSignMessage"]));
            }
            set {
                this["ComboBoxSignMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxSignMessageSelectedIndex {
            get {
                return ((int)(this["ComboBoxSignMessageSelectedIndex"]));
            }
            set {
                this["ComboBoxSignMessageSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignMonitorNumber {
            get {
                return ((string)(this["TextBoxSignMonitorNumber"]));
            }
            set {
                this["TextBoxSignMonitorNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignOffset {
            get {
                return ((string)(this["TextBoxSignOffset"]));
            }
            set {
                this["TextBoxSignOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxSignAlignment {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxSignAlignment"]));
            }
            set {
                this["ComboBoxSignAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxSignAlignmentSelectedIndex {
            get {
                return ((int)(this["ComboBoxSignAlignmentSelectedIndex"]));
            }
            set {
                this["ComboBoxSignAlignmentSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignMonitorWidth {
            get {
                return ((string)(this["TextBoxSignMonitorWidth"]));
            }
            set {
                this["TextBoxSignMonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxSignMonitorHeight {
            get {
                return ((string)(this["TextBoxSignMonitorHeight"]));
            }
            set {
                this["TextBoxSignMonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiMapMonitorHeight {
            get {
                return ((string)(this["TextBoxWikiMapMonitorHeight"]));
            }
            set {
                this["TextBoxWikiMapMonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiMapMonitorNumber {
            get {
                return ((string)(this["TextBoxWikiMapMonitorNumber"]));
            }
            set {
                this["TextBoxWikiMapMonitorNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiMapMonitorWidth {
            get {
                return ((string)(this["TextBoxWikiMapMonitorWidth"]));
            }
            set {
                this["TextBoxWikiMapMonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiMapOffset {
            get {
                return ((string)(this["TextBoxWikiMapOffset"]));
            }
            set {
                this["TextBoxWikiMapOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiMapAlignment {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiMapAlignment"]));
            }
            set {
                this["ComboBoxWikiMapAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiMapAlignmentSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiMapAlignmentSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiMapAlignmentSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiMapWindowSize {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiMapWindowSize"]));
            }
            set {
                this["ComboBoxWikiMapWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiMapWindowSizeSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiMapWindowSizeSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiMapWindowSizeSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiURL {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiURL"]));
            }
            set {
                this["ComboBoxWikiURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiURLSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiURLSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiURLSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiItemLinkColumn {
            get {
                return ((string)(this["TextBoxWikiItemLinkColumn"]));
            }
            set {
                this["TextBoxWikiItemLinkColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiDistance {
            get {
                return ((string)(this["TextBoxWikiDistance"]));
            }
            set {
                this["TextBoxWikiDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiStartingItem {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiStartingItem"]));
            }
            set {
                this["ComboBoxWikiStartingItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiStartingItemSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiStartingItemSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiStartingItemSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiFinishingItem {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiFinishingItem"]));
            }
            set {
                this["ComboBoxWikiFinishingItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiFinishingItemSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiFinishingItemSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiFinishingItemSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiTableNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiTableNames"]));
            }
            set {
                this["ComboBoxWikiTableNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiTableNamesSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiTableNamesSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiTableNamesSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiRoute {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiRoute"]));
            }
            set {
                this["ComboBoxWikiRoute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiRouteSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiRouteSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiRouteSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiURLMonitorNumber {
            get {
                return ((string)(this["TextBoxWikiURLMonitorNumber"]));
            }
            set {
                this["TextBoxWikiURLMonitorNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiURLOffset {
            get {
                return ((string)(this["TextBoxWikiURLOffset"]));
            }
            set {
                this["TextBoxWikiURLOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxWikiURLAlignment {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxWikiURLAlignment"]));
            }
            set {
                this["ComboBoxWikiURLAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxWikiURLAlignmentSelectedIndex {
            get {
                return ((int)(this["ComboBoxWikiURLAlignmentSelectedIndex"]));
            }
            set {
                this["ComboBoxWikiURLAlignmentSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiURLMonitorWidth {
            get {
                return ((string)(this["TextBoxWikiURLMonitorWidth"]));
            }
            set {
                this["TextBoxWikiURLMonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TextBoxWikiURLMonitorHeight {
            get {
                return ((string)(this["TextBoxWikiURLMonitorHeight"]));
            }
            set {
                this["TextBoxWikiURLMonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxWikiURLWindowHeight {
            get {
                return ((string)(this["TextBoxWikiURLWindowHeight"]));
            }
            set {
                this["TextBoxWikiURLWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxWikiURLWindowWidth {
            get {
                return ((string)(this["TextBoxWikiURLWindowWidth"]));
            }
            set {
                this["TextBoxWikiURLWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ComboBoxSettingsSimulatorVersion {
            get {
                return ((global::System.Drawing.Color)(this["ComboBoxSettingsSimulatorVersion"]));
            }
            set {
                this["ComboBoxSettingsSimulatorVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxSettingsSimulatorVersionSelectedIndex {
            get {
                return ((int)(this["ComboBoxSettingsSimulatorVersionSelectedIndex"]));
            }
            set {
                this["ComboBoxSettingsSimulatorVersionSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AircraftTitlesSelectedIndex {
            get {
                return ((int)(this["AircraftTitlesSelectedIndex"]));
            }
            set {
                this["AircraftTitlesSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxGeneralLocationCountry {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxGeneralLocationCountry"]));
            }
            set {
                this["ComboBoxGeneralLocationCountry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxGeneralLocationCountrySelectedIndex {
            get {
                return ((int)(this["ComboBoxGeneralLocationCountrySelectedIndex"]));
            }
            set {
                this["ComboBoxGeneralLocationCountrySelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxGeneralLocationState {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxGeneralLocationState"]));
            }
            set {
                this["ComboBoxGeneralLocationState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxGeneralLocationStateSelectedIndex {
            get {
                return ((int)(this["ComboBoxGeneralLocationStateSelectedIndex"]));
            }
            set {
                this["ComboBoxGeneralLocationStateSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ComboBoxGeneralLocationCity {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComboBoxGeneralLocationCity"]));
            }
            set {
                this["ComboBoxGeneralLocationCity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxGeneralLocationCitySelectedIndex {
            get {
                return ((int)(this["ComboBoxGeneralLocationCitySelectedIndex"]));
            }
            set {
                this["ComboBoxGeneralLocationCitySelectedIndex"] = value;
            }
        }
    }
}
